
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'chatllama'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '1234'
      # Allows the root user to connect from any host
      MYSQL_ROOT_HOST: '%'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - ./mysql:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    command: >
      /bin/bash -c "
      chmod 644 /etc/mysql/my.cnf &&
      docker-entrypoint.sh mysqld
      "
volumes:
  mysql:

networks:
  app-network:
    driver: bridge
