version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    command: nvidia-smi
    #runtime: nvidia
    #command: "--gpus=all"
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - app-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ "gpu" ]
              count: all

networks:
  app-network:
    driver: bridge
